<?php

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/functions.php';

requireRole('ngo');

$ngoId = $_SESSION['user_id'];

$successMessage = getFlash('profile_success', '');
$errors = getFlash('profile_errors', []);
$old = getFlash('profile_old', []);

$profileStatement = $pdo->prepare(
    "SELECT
        display_id,
        full_name,
        email,
        phone,
        organization_name,
        address,
        latitude,
        longitude,
        created_at
     FROM users
     WHERE user_id = ?
     LIMIT 1"
);

$profileStatement->execute([$ngoId]);
$profile = $profileStatement->fetch();

$field = function (string $key) use ($old, $profile) {
    return $old[$key] ?? $profile[$key] ?? '';
};

$pageTitle = 'Profile';
$activePage = 'profile';

require __DIR__ . '/../includes/layouts/header.php';
?>

<?php if ($successMessage): ?>
    <div class="alert alert-success"><?= e($successMessage) ?></div>
<?php endif; ?>

<?php if ($errors): ?>
    <div class="alert alert-error">
        <?php foreach ($errors as $error): ?>
            <p><?= e($error) ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<div class="panel stacked-panel">
    <div class="panel-head">
        <h3>Profile Overview</h3>
        <button class="button button-small button-outline" type="button" onclick="openEdit()">Edit Profile</button>
    </div>

    <div class="panel-body">
        <div class="profile-hero">
            <span class="profile-avatar"><?= e(strtoupper(substr($profile['full_name'], 0, 1))) ?></span>

            <div class="profile-hero-body">
                <div class="profile-name-row">
                    <h2 class="profile-name"><?= e($profile['full_name']) ?></h2>
                    <span class="badge badge-surplus">NGO Worker</span>
                </div>

                <ul class="profile-meta profile-meta-wide">
                    <li><span class="meta-icon">&#9993;</span><?= e($profile['email']) ?></li>
                    <li><span class="meta-icon">&#9742;</span><?= e($profile['phone']) ?></li>
                    <li><span class="meta-icon">&#9873;</span><?= e($profile['address']) ?></li>
                    <li><span class="meta-icon">&#128197;</span>Joined <?= date('d F Y', strtotime($profile['created_at'])) ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-head">
        <h3>Organization Information</h3>
        <button class="button button-small button-outline" type="button" onclick="openEdit()">Edit</button>
    </div>

    <div class="panel-body">
        <div class="info-grid">
            <div class="info-cell">
                <span class="info-label">NGO ID</span>
                <strong class="id-inline"><?= e($profile['display_id']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Organization Name</span>
                <strong><?= e($profile['organization_name']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Contact Person</span>
                <strong><?= e($profile['full_name']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Address</span>
                <strong><?= e($profile['address']) ?></strong>
            </div>
        </div>

        <p class="stat-note id-note">Your NGO ID is generated by the system and cannot be changed. It links every reservation to your organization.</p>
    </div>
</div>

<div class="modal" id="editModal">
    <div class="modal-card modal-wide">
        <h3>Edit Profile</h3>
        <p class="auth-subtitle">Your NGO ID cannot be changed.</p>

        <form method="POST" action="actions/update-profile.php" novalidate>
            <input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>">

            <div class="edit-columns">
                <div>
                    <h4 class="form-section-title">Account</h4>

                    <div class="field">
                        <label for="full_name">Full Name</label>
                        <input id="full_name" type="text" name="full_name" value="<?= e($field('full_name')) ?>" required>
                    </div>

                                <div class="field-row">
                <div class="field">
                    <label for="latitude">Latitude</label>
                    <input id="latitude" type="text" name="latitude" value="<?= e($field('latitude')) ?>" placeholder="e.g. 3.150000">
                </div>

                <div class="field">
                    <label for="longitude">Longitude</label>
                    <input id="longitude" type="text" name="longitude" value="<?= e($field('longitude')) ?>" placeholder="e.g. 101.700000">
                </div>
            </div>

            <p class="field-hint">
                Open Google Maps, right-click your office, and click the
                numbers that appear. Paste the first into Latitude and the
                second into Longitude. This lets FreshTrack show you how far
                each merchant is.
            </p>

                    <div class="field">
                        <label for="email">Email</label>
                        <input id="email" type="email" name="email" value="<?= e($field('email')) ?>" required>
                    </div>

                    <div class="field">
                        <label for="phone">Phone</label>
                        <input id="phone" type="text" name="phone" value="<?= e($field('phone')) ?>" required>
                    </div>
                </div>

                <div>
                    <h4 class="form-section-title">Organization</h4>

                    <div class="field">
                        <label for="organization_name">Organization Name</label>
                        <input id="organization_name" type="text" name="organization_name" value="<?= e($field('organization_name')) ?>" required>
                    </div>

                    <div class="field">
                        <label for="address">Address</label>
                        <input id="address" type="text" name="address" value="<?= e($field('address')) ?>" required>
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <button class="button" type="submit">Save Changes</button>
                <button class="button button-outline" type="button" onclick="closeEdit()">Cancel</button>
            </div>
        </form>
    </div>
</div>

<script>
    function openEdit() {
        document.getElementById('editModal').classList.add('modal-open');
    }

    function closeEdit() {
        document.getElementById('editModal').classList.remove('modal-open');
    }
</script>

<?php require __DIR__ . '/../includes/layouts/footer.php'; ?>