<?php

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/functions.php';

requireRole('merchant');
refreshInventoryStatus($pdo);

$merchantId = $_SESSION['user_id'];

$successMessage = getFlash('profile_success', '');
$errors = getFlash('profile_errors', []);
$old = getFlash('profile_old', []);

$profileStatement = $pdo->prepare(
    "SELECT
        display_id,
        full_name,
        email,
        phone,
        business_name,
        business_type,
        address,
        pickup_location,
        latitude,
        longitude,
        operating_hours,
        shop_image,
        created_at
     FROM users
     WHERE user_id = ?
     LIMIT 1"
);

$profileStatement->execute([$merchantId]);
$profile = $profileStatement->fetch();

// Falls back to the stored value when the form was not rejected.
$field = function (string $key) use ($old, $profile) {
    return $old[$key] ?? $profile[$key] ?? '';
};

$businessTypes = [
    'Grocery Store',
    'Bakery',
    'Supermarket',
    'Mini Market',
    'Other'
];

$pageTitle = 'Profile';
$activePage = 'profile';

require __DIR__ . '/../includes/layouts/header.php';
?>

<?php if ($successMessage): ?>
    <div class="alert alert-success"><?= e($successMessage) ?></div>
<?php endif; ?>

<?php if ($errors): ?>
    <div class="alert alert-error">
        <?php foreach ($errors as $error): ?>
            <p><?= e($error) ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<div class="panel stacked-panel">
    <div class="panel-head">
        <h3>Profile Overview</h3>
        <button class="button button-small button-outline" type="button" onclick="openEdit()">Edit Profile</button>
    </div>

    <div class="panel-body">
        <div class="profile-hero">
            <span class="profile-avatar"><?= e(strtoupper(substr($profile['full_name'], 0, 1))) ?></span>

            <div class="profile-hero-body">
                <div class="profile-name-row">
                    <h2 class="profile-name"><?= e($profile['full_name']) ?></h2>
                    <span class="badge badge-available">Merchant</span>
                </div>

                <ul class="profile-meta profile-meta-wide">
                    <li><span class="meta-icon">&#9993;</span><?= e($profile['email']) ?></li>
                    <li><span class="meta-icon">&#9742;</span><?= e($profile['phone']) ?></li>
                    <li><span class="meta-icon">&#9873;</span><?= e($profile['address'] ?: 'No address set') ?></li>
                    <li><span class="meta-icon">&#128197;</span>Joined <?= date('d F Y', strtotime($profile['created_at'])) ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-head">
        <h3>Business Information</h3>
        <button class="button button-small button-outline" type="button" onclick="openEdit()">Edit</button>
    </div>

    <div class="panel-body">
        <div class="info-grid">
            <div class="info-cell">
                <span class="info-label">Merchant ID</span>
                <strong class="id-inline"><?= e($profile['display_id']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Business Name</span>
                <strong><?= e($profile['business_name']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Business Type</span>
                <strong><?= e($profile['business_type']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Business Address</span>
                <strong><?= e($profile['address'] ?: 'Not set') ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Pickup Location</span>
                <strong><?= e($profile['pickup_location']) ?></strong>
            </div>

            <div class="info-cell">
                <span class="info-label">Operating Hours</span>
                <strong><?= e($profile['operating_hours'] ?: 'Not set') ?></strong>
            </div>
        </div>

        <p class="stat-note id-note">Your Merchant ID is generated by the system and cannot be changed. It links every item and reservation to your account.</p>
    </div>
</div>

<div class="modal" id="editModal">
    <div class="modal-card modal-wide">
        <h3>Edit Profile</h3>
        <p class="auth-subtitle">Your Merchant ID cannot be changed.</p>

            <form method="POST" action="actions/update-profile.php" enctype="multipart/form-data" novalidate>
            <input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>">

            <div class="edit-columns">
                <div>
                    <h4 class="form-section-title">Account</h4>

                    <div class="field">
                        <label for="full_name">Full Name</label>
                        <input id="full_name" type="text" name="full_name" value="<?= e($field('full_name')) ?>" required>
                    </div>

                    <div class="field">
                        <label for="email">Email</label>
                        <input id="email" type="email" name="email" value="<?= e($field('email')) ?>" required>
                    </div>

                    <div class="field">
                        <label for="phone">Phone</label>
                        <input id="phone" type="text" name="phone" value="<?= e($field('phone')) ?>" required>
                    </div>
                </div>

                <div>
                    <h4 class="form-section-title">Business</h4>

                    <div class="field">
                        <label for="business_name">Business Name</label>
                        <input id="business_name" type="text" name="business_name" value="<?= e($field('business_name')) ?>" required>
                    </div>

                    <div class="field">
                        <label for="business_type">Business Type</label>

                        <select id="business_type" name="business_type" required>
                            <?php foreach ($businessTypes as $type): ?>
                                <option value="<?= e($type) ?>" <?= $field('business_type') === $type ? 'selected' : '' ?>><?= e($type) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="field">
                        <label for="address">Business Address</label>
                        <input id="address" type="text" name="address" value="<?= e($field('address')) ?>">
                    </div>
                </div>
            </div>

            <div class="field-row">
                <div class="field">
                    <label for="pickup_location">Pickup Location</label>
                    <input id="pickup_location" type="text" name="pickup_location" value="<?= e($field('pickup_location')) ?>" required>
                </div>

                <div class="field">
                    <label for="operating_hours">Operating Hours</label>
                    <input id="operating_hours" type="text" name="operating_hours" value="<?= e($field('operating_hours')) ?>" placeholder="e.g. 8:00 AM - 10:00 PM Daily">
                </div>
            </div>

            <div class="field-row">
                <div class="field">
                    <label for="latitude">Latitude</label>
                    <input id="latitude" type="text" name="latitude" value="<?= e($field('latitude')) ?>" placeholder="e.g. 3.150000">
                </div>

                <div class="field">
                    <label for="longitude">Longitude</label>
                    <input id="longitude" type="text" name="longitude" value="<?= e($field('longitude')) ?>" placeholder="e.g. 101.700000">
                </div>
            </div>

            <p class="field-hint">
                Open Google Maps, right-click your shop, and click the numbers that appear.
                Paste the first into Latitude and the second into Longitude.
            </p>

                        <div class="field">
                <label for="shop_image">Shop Photo</label>

                <?php if (!empty($profile['shop_image'])): ?>
                    <div class="shop-image-current">
                        <?= shopCover($profile['shop_image'], $profile['business_name'], 'preview') ?>

                        <label class="shop-image-remove">
                            <input type="checkbox" name="remove_shop_image" value="1">
                            Remove this photo
                        </label>
                    </div>
                <?php endif; ?>

                <input id="shop_image" type="file" name="shop_image" accept="image/jpeg,image/png,image/webp">
                <p class="field-hint">
                    A photo of your shop front or interior. Landscape works
                    best — 1200 × 600 pixels or larger. JPG, PNG or WEBP,
                    up to 2 MB.
                </p>
            </div>

            <div class="form-actions">
                <button class="button" type="submit">Save Changes</button>
                <button class="button button-outline" type="button" onclick="closeEdit()">Cancel</button>
            </div>

        </form>
    </div>
</div>

<script>
    function openEdit() {
        document.getElementById('editModal').classList.add('modal-open');
    }

    function closeEdit() {
        document.getElementById('editModal').classList.remove('modal-open');
    }
</script>

<?php require __DIR__ . '/../includes/layouts/footer.php'; ?>